% Draw Figures - Chapter 3
%
% This script generates all of the figures that appear in
% Chapter 3 of the textbook.
%
% Nicholas O'Donoughue
% 25 May 2021

% Clear Figures
close all;

% Set up directory and filename for figures
dirNm = fullfile(pwd,'figures','practical_geo');
if ~exist(dirNm,'dir')
    mkdir(dirNm);
end
prefix = fullfile(dirNm,'fig3_');

% Initialize Plot Preference
doFullColor=true;
utils.initPlotSettings;

% Reset the random number generator, to ensure reproducability
rng('default') ; 
addpath('examples');

if ~exist('force_recalc','var')
    force_recalc = false;
end


%% Figure 1, TDOA Geometry -- non-redundant set

x_source = [2; 3];
x_sensor = [0, -1, 0, 1;
            0, -.5, 1, -.5];

ref_idx = 1;
test_idx = ~ismember(1:size(x_sensor,2), ref_idx);
x_ref = x_sensor(:, ref_idx);
x_test = x_sensor(:, test_idx);
% Plot sensor/source positions
fig1 = figure();
plot(x_source(1), x_source(2), 'k^', 'DisplayName','Source');
hold on;
plot(x_ref(1), x_ref(2,1), 'kv', 'DisplayName', 'Reference Sensor')
plot(x_test(1,:), x_test(2,:), 'ko', 'DisplayName','Sensor');

% Generate Isochrones
isochrone_label = 'Isochrones';
for ii = 1:size(x_test,2)
    this_x_test = x_test(:,ii);
    rdiff = utils.rngDiff(x_source, x_ref, this_x_test);
    xy_iso = tdoa.drawIsochrone(x_ref, this_x_test, rdiff, 10000, 5);

    hdl1=plot([x_ref(1), this_x_test(1)], [x_ref(2), this_x_test(2)], '-.', 'DisplayName', 'Sensor Pair');
    hdl2=plot(xy_iso(1, :), xy_iso(2, :), '-', 'Color', hdl1.Color, 'DisplayName',isochrone_label);
    if ii > 1
        utils.excludeFromLegend(hdl1);
        utils.excludeFromLegend(hdl2);
    end
end

xlim([-1 3]);
ylim([-1 3]);

legend('Location','NorthWest');
utils.setPlotStyle(gca,{'clean','tight'});
utils.exportPlot(fig1,[prefix '1']);

%% Figure 2, TDOA Geometry -- full set

x_source = [2; 3];
x_sensor = [0, -1, 0, 1;
            0, -.5, 1, -.5];

% Plot sensor/source positions
fig2 = figure();
plot(x_source(1), x_source(2), 'k^', 'DisplayName','Source');
hold on;
plot(x_sensor(1,:), x_sensor(2,:), 'ko', 'DisplayName','Sensor');

% Generate Isochrones
isochrone_label = 'Isochrones';
for ref_idx = 1:3
    x_ref = x_sensor(:,ref_idx);

    for test_idx = ref_idx+1:4
        x_test = x_sensor(:,test_idx);
        rdiff = utils.rngDiff(x_source, x_ref, x_test);
        xy_iso = tdoa.drawIsochrone(x_ref, x_test, rdiff, 10000, 5);

        hdl1=plot([x_ref(1), x_test(1)], [x_ref(2), x_test(2)], '-.', 'DisplayName', 'Sensor Pairs');
        hdl2=plot(xy_iso(1, :), xy_iso(2, :), '-', 'Color', hdl1.Color, 'DisplayName',isochrone_label);
        if ref_idx > 1 || test_idx > 2
            utils.excludeFromLegend(hdl1);
            utils.excludeFromLegend(hdl2);
        end
    end
end
xlim([-1 3]);
ylim([-1 3]);
legend('Location','NorthWest');
utils.setPlotStyle(gca,{'clean','tight'});
utils.exportPlot(fig2,[prefix '2']);


%% Figures 4 a, b, 5
% Figures generated by Example 3.1

figs = book2_ex3_1();

suffixes = {'4a', '4b', '5'};
for idx = 1:numel(figs)
    figure(figs(idx));
    
    grid off;
    utils.exportPlot(figs(idx), [prefix suffixes{idx}],true);
end

%% Figures 6, and 7abcde

figs = book2_ex3_2();

figure(figs(1));
utils.setPlotStyle(gca,{'widescreen','equal','tight'});
utils.exportPlot(figs(1), [prefix, '6']);
for idx = 2:numel(figs)
    utils.exportPlot(figs(idx), [prefix '7' char('a' + idx-2)],true);
end

%% Figures 9 and 10abc

figs = book2_ex3_3();

figure(figs(1));
utils.setPlotStyle(gca,{'widescreen','equal','tight'});
utils.exportPlot(figs(1), [prefix, '9']);
for idx = 2:numel(figs)
    utils.exportPlot(figs(idx), [prefix '10' char('a' + idx-2)], true);
end

%% Figures 11 and 12
if force_recalc
    figs = book2_ex3_4();
    
    suffixes = {'11', '12'};
    for idx = 1:numel(figs)
        figure(figs(idx));
        utils.setPlotStyle(gca,{'widescreen','tight'});
        utils.exportPlot(figs(idx), [prefix suffixes{idx}]);
    end
    
    xlim([1.6,4.4]);
    ylim([3.2,4.8]);
    utils.exportPlot(figs(end), [prefix '12_zoom']);
end

%% Cleanup

% Restore plot settings
utils.resetPlotSettings;